name: Deploy frontend
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist"
          target: "/var/www/dobox-frontend"
